#!/bin/bash

cmd_dir=$(dirname "$0")
data_dir=$cmd_dir/../usr/share/nesemu

nesemu="$cmd_dir/nesemu"
nesemu_cpu="$cmd_dir/nesemu-cpu"
nesemu_cartridge="$cmd_dir/nesemu-cartridge"

echo "Running nesemu with color test rom"
echo "exit" | $nesemu $data_dir/color_test_nosprites.nes -D

echo "a9778dffff" | xxd -r -p | LOG_LEVEL=trace $nesemu_cpu 6

$nesemu_cartridge $data_dir/color_test_nosprites.nes
